#!/usr/bin/env bash

# Used by Docker Hub to replace the normal autobuild build script

# Linux Builds
docker build --no-cache -t engineervix/pyinstaller-linux:python3 -t engineervix/pyinstaller-linux:latest . --network=host
