#!/usr/bin/env bash

# Used by Docker Hub to replace the normal autobuild build script

# Windows Python2 (32-bit) Build
docker build --no-cache -t engineervix/pyinstaller-windows:python2 . --network=host
